---
  title: "Schedule"
---
  
  **Click on the text like "Week 1: Jan 20 -- 24" to expand or collapse the items we covered in that week.**
  
  I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
      sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", TRUE, "Week 1: Jan 20 -- Jan 24", "

#### Wed, Jan 22
 * **In class**, we will work on:
    * Discuss [syllabus](syllabus/syllabus_stat_344ne.pdf), overview of course
    * Warm up examples:
        * Example 1: [pdf](materials/20200122_intro/20200122_ex1.pdf)
        * Example 2: [pdf](materials/20200122_intro/20200122_ex2.pdf)
        * Example 3: [pdf](materials/20200122_intro/20200122_ex3.pdf)
        * Lecture notes: [pdf](materials/20200122_intro/lecture_notes.pdf)
        * Python notebook: https://github.com/mhc-stat344ne-s2020/20200122_examples/blob/master/20200122_examples.ipynb
 * **After class**, please:
    * **Register for GitHub** [here](https://github.com) if you haven't already; I will ask you to provide your GitHub user name in the questionairre below.
    * **Fill out** a brief [questionnairre](https://docs.google.com/forms/d/e/1FAIpQLSfw9sGTYsHaA9D0NEuxLVVdD4QlQXDk59DFu0-E6KxLtnEhxw/viewform?usp=sf_link) (if you are taking two classes with me, you only need to fill out this questionairre once)
    * **Fill out** this brief [poll about when my office hours should be held](https://zvite.co/i/JbeK8Cyi) (if you are taking two classes with me, you only need to fill out this poll once)
    * **Sign up** for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/spring2020/stat344ne](https://piazza.com/mtholyoke/spring2020/stat344ne)
    * **Reading**
        * Chollet:
            * Skim sections 1.1 -- 1.3.  This is pretty fluffy and we'll mostly either skip it or talk about it in much more depth later, but it might be nice to see now for a little context.
            * Read sections 2.1 -- 2.3 more carefully.  We will talk about this over the next day or two.
        * Goodfellow et al.:
            * Read the intro to section 5.5 (but don't worry about KL divergence), read section 5.5.1, lightly skim section 6.1, read the first 3 paragraphs of section 6.2.1.1, and skim sections 6.2.2.1, 6.2.2.2, and 6.2.2.3.  We will talk about this over the next day or two.
    * **Videos**
        * Some of you may find these videos helpful:
            * [Broadcasting in NumPy](https://www.youtube.com/watch?v=tKcLaGdvabM) -- This is among my least favorite examples, apologies!
            * [Softmax regression](https://www.youtube.com/watch?v=LLux1SW--oM)
    * **Homework 0** due 5 pm Wed, Jan 29


#### Fri, Jan 24
 * **In class**, we will work on:
    * Maximum likelihood and output activations for regression, binary classification, and multi-class classification
 * **After class**, please:
    * **Reading**
        * Continue/finish readings listed for Wed, Jan 22.
")

#    * **Videos**
#        * Some of you may find this sequence of three videos introducing Keras helpful (note that I will follow the code in Chollet, which differs slightly from code used in these videos):
#            * Video 1: [data set up](https://www.youtube.com/watch?v=UkzhouEk6uY&list=PLZbbT5o_s2xrwRnXk_yCPtnqqo4_u2YGL&index=3)
#            * Video 2: [defining the network](https://www.youtube.com/watch?v=Boo6SmgmHuM&list=PLZbbT5o_s2xrwRnXk_yCPtnqqo4_u2YGL&index=4)
#            * Video 3: [training models](https://www.youtube.com/watch?v=EHbay6hDZGA&list=PLZbbT5o_s2xrwRnXk_yCPtnqqo4_u2YGL&index=5)
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", TRUE, "Week 2: Jan 27 -- Jan 31", "
#### Mon, Jan 27
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Jan 29
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Jan 31
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", TRUE, "Week 3: Feb 03 -- Feb 07", "
#### Mon, Feb 03
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Feb 05
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Feb 07
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", TRUE, "Week 4: Feb 10 -- Feb 14", "
#### Mon, Feb 10
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Feb 12
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Feb 14
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", TRUE, "Week 5: Feb 17 -- Feb 21", "
#### Mon, Feb 17
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Feb 19
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Feb 21
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", TRUE, "Week 6: Feb 24 -- Feb 28", "
#### Mon, Feb 24
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Feb 26
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Feb 28
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", TRUE, "Week 7: Mar 02 -- Mar 06", "
#### Mon, Mar 02
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Mar 04
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Mar 06
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", TRUE, "Week 8: Mar 09 -- Mar 13", "
#### Mon, Mar 09
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Mar 11
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Mar 13
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", TRUE, "Week 9: Mar 16 -- Mar 20", "
#### Mon, Mar 16
 * **No Class**: Midsemester Break.  Safe travels!


#### Wed, Mar 18
 * **No Class**: Midsemester Break.  Safe travels!


#### Fri, Mar 20
 * **No Class**: Midsemester Break.  Safe travels!
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", TRUE, "Week 10: Mar 23 -- Mar 27", "
#### Mon, Mar 23
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Mar 25
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Mar 27
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", TRUE, "Week 11: Mar 30 -- Apr 03", "
#### Mon, Mar 30
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Apr 01
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Apr 03
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", TRUE, "Week 12: Apr 06 -- Apr 10", "
#### Mon, Apr 06
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Apr 08
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Apr 10
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", TRUE, "Week 13: Apr 13 -- Apr 17", "
#### Mon, Apr 13
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Apr 15
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Apr 17
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", TRUE, "Week 14: Apr 20 -- Apr 24", "
#### Mon, Apr 20
 * **In class**, we will work on:
 * **After class**, please:


#### Wed, Apr 22
 * **In class**, we will work on:
 * **After class**, please:


#### Fri, Apr 24
 * **In class**, we will work on:
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", TRUE, "Week 15: Apr 27 -- May 01", "
#### Mon, Apr 27
 * **In class**, we will work on:
 * **After class**, please:


")
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: May 04 -- May 08", "We will not have a final exam in this class.")
```

